# ⚙️ DRAGONFORGE CONFIGURATION

# --- DIFFICULTY SCALING ---
ENEMY_HP_MULT = 1.0
ENEMY_DMG_MULT = 1.0
XP_GAIN_MULT = 1.0
COIN_DROP_MULT = 1.0

# --- PLAYER STARTING STATS ---
STARTING_HP = 250
STARTING_MP = 120
STARTING_COINS = 300
LEVEL_UP_HP_GAIN = 40
LEVEL_UP_MP_GAIN = 25

# --- BATTLE SETTINGS ---
GRID_SIZE_NORMAL = 10
GRID_SIZE_BOSS = 15
POTION_HEAL_AMOUNT = 120
MANA_RESTORE_AMOUNT = 60

# --- FINAL BOSS (DREAD KNIGHT) TUNING ---
BOSS_STAGE_1_HP = 1200
BOSS_STAGE_2_HP = 1200
BOSS_STAGE_3_HP = 1800
BOSS_STAGE_4_HP = 2000
BOSS_REGEN_PER_TURN = 60
